"""empty message

Revision ID: c916cf0b52f8
Revises: 
Create Date: 2023-09-20 13:37:25.475648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c916cf0b52f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactus',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('contact_id')
    )
    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'state', ['state_id'], ['state_id'])
        batch_op.drop_column('lga_name')

    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('lga', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lga_name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('contactus')
    # ### end Alembic commands ###
